version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: agwiki
      MYSQL_USER: mysql_root
      MYSQL_PASSWORD: mysql_root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: